### ISSUE TITLE
the internal parameters of the camera are needed to reconstruct the feature key points and calculate the E/F matrix.

### ISSUE THREAD

**Issue by ahong007007** [vcg-uvic/acne#3]
Thank you for your excellent work.

I found that in the demo.ipynb code, the internal parameters of the camera are needed to reconstruct the feature key points and calculate the E/F matrix.

I did not see the relevant introduction in the paper summary. Is the internal parameter of the image necessary? The algorithm cannot calculate the E/F matrix without the internal parameter. Thank you, and look forward to your reply.

**Comment by wsunid** [comment]
Hi,

Thanks for your interest in our work.

We don't need the intrinsics to compute the F matrix.  But we do need the intrinsics for the E matrix because calibrated coordinates of feature points are required in this case.

In my demo code, it's a bit confusing that function `prepare_xs` takes in the calibration matrix (K) for both E and F matrix. But if you look at the function `get_T_from_K`, you will find that it only uses the image size information from K (i.e., cx, cy) for the F matrix in order to normalize the feature points. It means that you could also use the image size (w, h) directly.

We have described the normalization of point coordinates (for F matrix) in part 4.3 of our paper. Basically, in the case of the F matrix, we utilize the image size to normalize the coordinates for the numerical stability of the 8-point algorithm. 

Feel free to let me know if you have further questions :)) 

Best,
Weiwei.
